version: '3.8'

services:
  app:
    image: php:8.4-cli
    container_name: geoapp_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - geonetwork
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgis/postgis:17-3.5
    container_name: geoapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: geoapp_user
      POSTGRES_PASSWORD: geoapp_password
      POSTGRES_DB: geoapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geonetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geoapp_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  geonetwork:
    driver: bridge





